version: '3'
services:
  micro-service-1:
    build: ./LambdaDocker
    container_name: micro-service-1
    ports:
      - 8080:8080
  micro-service-2:
    build: ./LambdaDocker2
    container_name: micro-service-2
    ports:
      - 8090:8080

    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=value
    #   - MONGO_INITDB_ROOT_PASSWORD=""

