service: aws-node-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  ecr:
    images:
      image-courses:
        path: ./LambdaDocker
      image-books:
        path: ./LambdaDocker2
  environment:
    DATABASE_URL: file:../mnt/efs/data/database.db
    DB_TYPE: sqlite

    LAMBDA_SG: "sg-06b50d022aa8be3e6"
    LAMBDA_SUBNET: "subnet-03084a940d820e926"
    EFS_ID: "fs-016244060c4e19d9f"
    ACCESS_POINT: "arn:aws:elasticfilesystem:us-east-1:778316472973:access-point/fsap-039228fbb53486976"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - elasticfilesystem:ClientMount
        - elasticfilesystem:ClientRootAccess
        - elasticfilesystem:ClientWrite
        - elasticfilesystem:DescribeMountTargets
      Resource: "*"
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetWorkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: "*"

functions:
  ms-courses:
    timeout: 30
    # memorySize: 10000
    image:
      name: image-courses
    vpc:
      securityGroupIds:
        - ${self:provider.environment.LAMBDA_SG}
      subnetIds:
        - ${self:provider.environment.LAMBDA_SUBNET}
    events:
      - httpApi:
          path: /course/{proxy+}
          method: ANY
          cors: true
    fileSystemConfig:
      # ARN of EFS Access Point
      arn: ${self:provider.environment.ACCESS_POINT}
      # Path under which EFS will be mounted and accessible in Lambda
      localMountPath: /mnt/efs
  # ms-books:
  #   timeout: 30
  #   # memorySize: 10000
  #   image:
  #     name: image-books
  #   vpc:
  #     securityGroupIds:
  #       - ${self:provider.environment.LAMBDA_SG}
  #     subnetIds:
  #       - ${self:provider.environment.LAMBDA_SUBNET}
  #   events:
  #     - httpApi:
  #         path: /books/{proxy+}
  #         method: ANY
  #         cors: true
  #   fileSystemConfig:
  #     # ARN of EFS Access Point
  #     arn: ${self:provider.environment.ACCESS_POINT}
  #     # Path under which EFS will be mounted and accessible in Lambda
  #     localMountPath: /mnt/efs
